In [3]:
print("Hello World")

Hello World


In [6]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
b = np.where(a == 1)
print(b)

(array([0]),)


In [7]:
a = np.linspace(0,10,100)
a

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [73]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
y = np.array([0,1,0,1])

classes = np.unique(y)

indexed_class  = []
for i in classes:
    class_i = np.where(y == i) 
    indexed_class.append(class_i[0])
print(indexed_class)


[array([0, 2]), array([1, 3])]


In [74]:
np.random.seed(42)
shuffled_class  = []
for i in indexed_class:
    shuffle = np.random.permutation(i.size)
    shuffled_class.append(i[shuffle])

print(shuffled_class)
test_size = 0.5
train_index = []
test_index = []
for i in shuffled_class:
    train_nums = int(i.size * (1-test_size))
    train_index.append(i[: train_nums])
    test_index.append(i[train_nums: ])

train_index = np.concatenate(train_index)
test_index = np.concatenate(test_index) 

[array([2, 0]), array([1, 3])]


### Tại sao phiên bản này lại sai !?



In [3]:
def train_test_split(X, y, test_size = 0.2, random_state = None):
    rng = np.random.default_rng(random_state)
    
    classes = np.unique(y)

    indexed_class  = []
    for i in classes:
        class_i = np.where(y == i) 
        indexed_class.append(class_i[0])   
        
    shuffled_class  = []
    for i in indexed_class:
        shuffled_class.append(rng.permutation(i))

    train_index = []
    test_index = []
    for i in shuffled_class:
        train_nums = int(i.size * (1 - test_size))
        train_index.append(i[: train_nums])
        test_index.append(i[train_nums: ])

    train_index = np.concatenate(train_index)
    test_index = np.concatenate(test_index)

    # shuffle
    train_index = rng.permutation(train_index)
    test_index = rng.permutation(test_index)
    return X[train_index], X[test_index], y[train_index], y[test_index] 
    

### Phiên bản chuẩn !!!

In [14]:
def allocated_func(num_samples, class_count, rng, test_size):
    n_test = int(np.ceil(num_samples * test_size))  
    expected = class_count / num_samples * n_test
    allocated = np.floor(expected).astype(np.int32)
    remaining = n_test - allocated.sum()
    remainders = expected - allocated
    for _ in range(remaining):
        max_remainder = remainders.max()

        candidates = np.flatnonzero(
            np.isclose(remainders, max_remainder)
        )

        selected = rng.choice(candidates)

        allocated[selected] += 1
        remainders[selected] = -1

    return allocated

In [24]:
def train_test_split(X, y, test_size = 0.2, random_state = None):
    num_samples = y.size

    rng = np.random.default_rng(random_state)
    
    classes = np.unique(y)

    indexed_class  = []
    for i in classes:
        class_i = np.where(y == i)      # np.where -> tuple 
        indexed_class.append(class_i[0])   

    class_count = np.array([i.size for i in indexed_class])

    shuffled_class  = []
    for i in indexed_class:
        shuffled_class.append(rng.permutation(i))

    allocated = allocated_func(num_samples, class_count, rng, test_size)

    train_index = []
    test_index = []
    for i, j in zip(shuffled_class, allocated):
        train_index.append(i[j:])
        test_index.append(i[:j])

    train_index = np.concatenate(train_index)
    test_index = np.concatenate(test_index)

    # shuffle
    train_index = rng.permutation(train_index)
    test_index = rng.permutation(test_index)
    return [X[train_index], X[test_index], y[train_index], y[test_index]]

In [19]:
X = np.random.standard_normal((4,3))
y = np.array([1,0,0,1])

In [25]:
print(type(train_test_split(X,y, test_size = 0.2)))

<class 'list'>


In [12]:
class_0_index  = np.where(y == 0)
class_1_index = np.where(y == 1)

print(X[class_0_index])
print(X[class_1_index])

[[1 2 3]
 [7 8 9]]
[[ 4  5  6]
 [10 11 12]]


In [13]:
print(int(0.8))

0
